var siteMap = {
        " β-HCH": "NHL (Non-hodgkin's lymphoma)",
        "(Oesophagus squamous cell esophageal carcinoma)": "Oesophagus",
        "171": "Other (specify)",
        "177": "Prostate",
        "34.0-34.9": "Lung",
        "ALL": "Leukemia (ALL (Acute lymphoblastic/lymphocytic leukemia))",
        "AML": "Leukemia (AML (Acute myeloid leukemia))",
        "ANL": "Leukemia (AML (Acute myeloid leukemia))",
        "Acute myeloid leukemia": "Leukemia (AML (Acute myeloid leukemia))",
        "Adenocarcinomas": "Lung (Adenocarcinoma)",
        "Adenocarcinomas of the esophagus and gastric cardia (ICD 150.0-150.9 and ICD 151.0)": "Stomach/gastric cancer",
        "Agressive prostate cancer": "Prostate (Aggressive/Advanced)",
        "All Leukemias (AML, ALL, CML, CLL)": "Leukemia",
        "All cancer": "All cancers combined",
        "All cancer 140-209": "All cancers combined",
        "All cancers": "All cancers combined",
        "All causes 001-999": "All cancers combined",
        "All leukemia": "Leukemia",
        "All lung cancers": "Lung",
        "All lymphohematopoietic (ICD 200-209)": "Lymphatic and hematopoetic",
        "All lymphoid neoplasms": "Lymphatic and hematopoetic",
        "All neoplams": "All cancers combined",
        "All sites": "All cancers combined",
        "B cell lymphoma": "B-cell lymphoma",
        "B-cell lymphoma": "B-cell lymphoma",
        "B-cell lymphoma (highgrade)": "B-cell lymphoma",
        "B-cell lymphoma (low grade)": "B-cell lymphoma",
        "B-cell lymphomas": "B-cell lymphoma",
        "Bladder": "Urinary bladder",
        "Bladder (188)": "Urinary bladder",
        "Bladder (C67.0-C67.9)": "Urinary bladder",
        "Bladder (ICD-10 C67)": "Urinary bladder",
        "Bladder incidence": "Urinary bladder",
        "Bladder mortality": "Urinary bladder",
        "Brain (191)": "Brain",
        "Brain gliomas (ICD-O 938-948)": "Brain",
        "Breast": "Breast",
        "Breast ": "Breast",
        "Breast (174)": "Breast",
        "Breast (ICD-O 2nd C50.0-C50.9)": "Breast",
        "Breast Cancer": "Breast",
        "Breast cancer": "Breast",
        "Breast cancer ": "Breast",
        "Breast cancer (diagnosed 1988-1994)": "Breast",
        "Breast cancer (diagnosed 1995-2001)": "Breast",
        "Buccal cavity & pharynx": "Pharynx",
        "C61": "Prostate",
        "C61 lethal prostate cancer": "Prostate (Aggressive/Advanced)",
        "C61 prostate cancer, blacks": "Prostate (Aggressive/Advanced)",
        "C61 prostate cancer, whites": "Prostate (Aggressive/Advanced)",
        "CLL": "NHL (CLL (chronic lymphocytic leukemia))",
        "CLL/SLL": "NHL (SLL/CLL)",
        "CML": "Leukemia (CML (Chronic myeloid leukemia))",
        "Cancer of the exocrine pancreas": "Pancreas",
        "Childhood Acute Lymphocytic Leukemia": "Leukemia (Childhood cancer)",
        "Childhood cancer": "Childhood cancer",
        "Childhood leukemia": "Leukemia (Childhood cancer)",
        "Chronic lymphocytic leukemia and small lymphocytic lymphoma": "NHL (SLL/CLL)",
        "Chronic lymphoid leukemia": "Leukemia (Lymphoid)",
        "Chronic myeloid leukemia": "Leukemia (CML (Chronic myeloid leukemia))",
        "Colon": "Colon",
        "Colon  (C18)": "Colon",
        "Colon  (C18) ": "Colon",
        "Colon  ICD-10 C18.0–C18.9 and C19": "Colon",
        "Colon (C18) , males": "Colon",
        "Colon (C18), among men and women combined": "Colon",
        "Colon (C18), among men only": "Colon",
        "Colon (C18), among women only": "Colon",
        "Colon (C18), females": "Colon",
        "Colon (C18.0-C18.9), both": "Colon",
        "Colon (C18.0-C18.9), females": "Colon",
        "Colon (C18.0-C18.9), males": "Colon",
        "Colon (C180-C189)": "Colon",
        "Colon Cancer, causcasians (257 cases)": "Colon",
        "Colon cancer": "Colon",
        "Colon cancer (9th revision ICD 153.0-153.8)": "Colon",
        "Colon cancer (C18), 855 cases": "Colon",
        "Colon cancer (ICD-O-1: 153.0-153.9)": "Colon",
        "Colon cancer (ICD-O-2: C180-188)": "Colon",
        "Colon cancer (ICD-O-2: C180-C188)": "Colon",
        "Colon cancer (females)": "Colon",
        "Colon cancer (males)": "Colon",
        "Colon cancer APC+ (ICD-O: 153.0-153.7)": "Colon",
        "Colon cancer APC+(ICD-O: 153.0-153.7)": "Colon",
        "Colon cancer APC- (ICD-O: 153.0-153.7)": "Colon",
        "Colon cancer APC-(ICD-O: 153.0-153.7)": "Colon",
        "Colon cancer among females": "Colon",
        "Colon cancer among males": "Colon",
        "Colon cancer among men only": "Colon",
        "Colon cancer among women only": "Colon",
        "Colon cancer, among carriers of 0 alleles for CYP2E1 96-bp insertion": "Colon",
        "Colon cancer, among carriers of 1 or 2 alleles for CYP2E1 96-bp insertion": "Colon",
        "Colon cancer, females": "Colon",
        "Colon cancer, females  (International Classification of Diseases for Oncology Edition 2 codes 18.0 and 18.2–18.9)": "Colon",
        "Colon cancer, females  (International Classification of Diseases for Oncology code 153)": "Colon",
        "Colon cancer, males": "Colon",
        "Colon cancer, males  (International Classification of Diseases for Oncology Edition 2 codes 18.0 and 18.2–18.9)": "Colon",
        "Colon, 236 cases": "Colon",
        "Colon, 283 cases": "Colon",
        "Colon, females": "Colon",
        "Colon, males": "Colon",
        "Colon, men and women": "Colon",
        "Colon,428 cases": "Colon & rectum",
        "Colorecta cancer": "Colon & rectum",
        "Colorectal": "Colon & rectum",
        "Colorectal (C18, C19, C20)": "Colon & rectum",
        "Colorectal (C180-C189, C199, C209, C260)": "Colon & rectum",
        "Colorectal cancer": "Colon & rectum",
        "Colorectal cancer ": "Colon & rectum",
        "Colorectal cancer (ICD-O-2: C180-C189, C199, C209)": "Colon & rectum",
        "Colorectal cancer (ICD9 153, 154.0 or 154.1 or ICD10 C18, C19 or C20)": "Colon & rectum",
        "Colorectal cancer (International Classification of Diseases – 9th revision codes 153.0-153.9, 154.1-154.3, 154.8)": "Colon & rectum",
        "Colorectal cancer (females)": "Colon & rectum",
        "Colorectal cancer (males)": "Colon & rectum",
        "Colorectal cancer (men)": "Colon & rectum",
        "Colorectal cancer MMR deficient": "Colon & rectum",
        "Colorectal cancer MMR proficient": "Colon & rectum",
        "Colorectal cancer among females": "Colon & rectum",
        "Colorectal cancer among males": "Colon & rectum",
        "Colorectal cancer among males and females": "Colon & rectum",
        "Colorectal cancer p53+": "Colon & rectum",
        "Colorectal cancer p53-": "Colon & rectum",
        "Colorectal cancer stratified by MDR1 C3435T": "Colon & rectum",
        "Colorectal cancer stratified by MDR1 rs3789243 ": "Colon & rectum",
        "Colorectal cancer stratified by NFkB -94 del polymorphism": "Colon & rectum",
        "Colorectal cancer, 100 cases": "Colon & rectum",
        "Colorectal cancer, 487 cases": "Colon & rectum",
        "Colorectal cancer, GSTM1 genotype null": "Colon & rectum",
        "Colorectal cancer, GSTM1 genotype present": "Colon & rectum",
        "Colorectal cancer, ICD-10 10th revision, C18-C20)": "Colon & rectum",
        "Colorectal cancer, ICD-10 10th revision, C18-C20) ": "Colon & rectum",
        "Colorectal cancer, fast NAT1": "Colon & rectum",
        "Colorectal cancer, fast and intermediate NAT2": "Colon & rectum",
        "Colorectal cancer, females": "Colon & rectum",
        "Colorectal cancer, males": "Colon & rectum",
        "Colorectal cancer, males and females": "Colon & rectum",
        "Colorectal cancer, slow and nomal NAT1": "Colon & rectum",
        "Colorectal cancer, slow and nomal NAT2": "Colon & rectum",
        "Colorectal cancer, slow and normal NAT1": "Colon & rectum",
        "Colorectal cancer-MSI-H": "Colon & rectum",
        "Colorectal cancer-MSS/L": "Colon & rectum",
        "Colorectal cancer[International Classification of Diseases, Ninth Revision (ICD-9) codes 153.0-153.9 and International Classification of Diseases, Tenth Revision (ICD- 10) codes C18.0-C18.9] ": "Colon & rectum",
        "Colorectal, 371 cases": "Colon & rectum",
        "Colorectal, 394 cases": "Colon & rectum",
        "Colorectal, 617 cases": "Colon & rectum",
        "Colorectal, 961 cases": "Colon & rectum",
        "Colorectal, NAT1 fast": "Colon & rectum",
        "Colorectal, NAT1 slow": "Colon & rectum",
        "Colorectal, NAT2 fast": "Colon & rectum",
        "Colorectal, NAT2 slow": "Colon & rectum",
        "Colorectum": "Colon & rectum",
        "Colorectum (C180-C189, C199, C209, C260)": "Colon & rectum",
        "Colorectum (C180-C189, C199, C209, C260) ": "Colon & rectum",
        "Colorectum, 733 cases": "Colon & rectum",
        "Confirmed pathologically and the remaining cases were diagnosed clinically, all of them were diagnosed by CT scan, echography, and ERCP and/or PTC together with biochemical markers.": "Other (specify)",
        "DLBC": "NHL (DLBCL (Diffuse large B-cell lymphoma))",
        "DLBCL": "NHL (DLBCL (Diffuse large B-cell lymphoma))",
        "Diffuse  NHL": "NHL (Non-hodgkin's lymphoma)",
        "Diffuse B-cell  lymphoma": "NHL (DLBCL (Diffuse large B-cell lymphoma))",
        "Diffuse lage B cell lymphoma": "NHL (DLBCL (Diffuse large B-cell lymphoma))",
        "Diffuse large B-cell lymphoma": "NHL (DLBCL (Diffuse large B-cell lymphoma))",
        "Distal (C18.6-18.7) , males": "Colon & rectum",
        "Distal colon": "Colon & rectum",
        "Distal colon (C18.6-18.7), females": "Colon & rectum",
        "Distal colon (C185-C187)": "Colon & rectum",
        "Distal colon (ICD-O version 2), females": "Colon & rectum",
        "Distal colon (ICD-O version 2), males": "Colon & rectum",
        "Distal colon (descending to sigmoid colon), both genders": "Colon & rectum",
        "Distal colon , males": "Colon & rectum",
        "Distal colon both genders": "Colon & rectum",
        "Distal colon cancer": "Colon & rectum",
        "Distal colon, 155 cases": "Colon & rectum",
        "Distal colon, females": "Colon & rectum",
        "Distal stomach adenocarcinoma": "Stomach/gastric cancer",
        "EAC": "Oesophagus (Adenocarcinoma)",
        "ESCC": "Oesophagus (Squamous cell carcinoma)",
        "ESCCcases with a pathologic conﬁrmation (ICD-10 code C15)": "Oesophagus (Squamous cell carcinoma)",
        "ESCCcases with a pathologic conﬁrmation (ICD-10 code C15) ": "Oesophagus (Squamous cell carcinoma)",
        "Ephitelial ovarian cancer": "Ovary",
        "Esophageal adenocarcinoma": "Oesophagus (Adenocarcinoma)",
        "Esophageal adenocarcinoma (ICD10)": "Oesophagus (Adenocarcinoma)",
        "Esophageal squamous cell carcinoma": "Oesophagus (Squamous cell carcinoma)",
        "Esophageal squamous cell carsinoma": "Oesophagus (Squamous cell carcinoma)",
        "Esophagenal adenocarcinoma (C15.0-C15.9)": "Oesophagus (Adenocarcinoma)",
        "Esophagus": "Oesophagus",
        "Esophagus ICD-O-3": "Oesophagus",
        "Esophagus cancer (ICD8, 146 and 148)": "Oesophagus",
        "Esophagus carcinomas included squamous cell carcinomas C15, histology codes: 8050–8076, and adenocarcinomas C15, histology codes: 8140, 8141, 8190–8231, 8260–8263, 8310, 8430, 8480–8490, 8560, and 8570–8572.": "Oesophagus",
        "Follicular": "NHL (Follicular)",
        "Follicular B cell": "NHL (Follicular)",
        "Follicular NHL": "NHL (Follicular)",
        "Follicular, grade I–III": "NHL (Follicular)",
        "Gallbladder": "Bile duct/Gallbladder",
        "Gastric cancer was classified as cardia adenocarcinomas C16.0 and non-cardia adenocarcinomas C16.1–C16.9, including overlapping (C16.8) and not otherwise specified (C16.9) tumors.": "Stomach/gastric cancer",
        "Gastric cardia adenocarcinoma": "Stomach/gastric cancer",
        "Gastric cardia adenocarcinoma (C16.0)": "Stomach/gastric cancer",
        "Gastric distal adenocarcinoma (C16.1-C16.9)": "Stomach/gastric cancer",
        "Gastric noncardia adenocarcinoma": "Stomach/gastric cancer",
        "Granulocytic leukemia": "Leukemia",
        "HCL": "NHL (HCL (Hairy cell leukemia))",
        "HL": "NHL (HCL (Hairy cell leukemia))",
        "HL (ICDO2 included nodular sclerosis (M9656/3; M9663/3; M9664/3; M9665/3; M9666/3; M9667/3), lymphocytic predominance (M9651/3; M9657/3; M9658/3; M9659/3), mixed cellularity (M9652/3), lymphocytic depletion (M9653/3; M9654/3), miscellaneous (other M9650-M9669 codes for HL)": "HL (Hodgkin's lymphoma)",
        "Hairy Cell Leukemia": "NHL (HCL (Hairy cell leukemia))",
        "Hairy cell leukemia": "NHL (HCL (Hairy cell leukemia))",
        "High stage prostate cancer": "Prostate (Aggressive/Advanced)",
        "High-stage prostate cancer": "Prostate (Aggressive/Advanced)",
        "Hodgkin lymphoma": "HL (Hodgkin's lymphoma)",
        "ICD -7 154 46 cases of rectal cancer": "Rectum",
        "ICD 9 185": "Prostate",
        "ICD-10": "Pancreas",
        "ICD-7 153 63 cases of colon cancer": "Colon",
        "ICD-7 153-154, 109 cases of colorectal cancer": "Colon & rectum",
        "ICD-9": "Other (specify)",
        "ICD-9 code 153 (colon) and 154 (rectum)": "Colon & rectum",
        "ICD-9 code 153 (colon) and code 154.0 (rectosigmoid junction)": "Colon & rectum",
        "ICD-O C34": "Other (specify)",
        "ICD-O-2": "Other (specify)",
        "ICDO-2  (C25 Pancreas)": "Pancreas",
        "ICDO-3": "Other (specify)",
        "ICDO-3 (Pancreas: C25.0–25.9)": "Pancreas",
        "Kidney ": "Kidney",
        "Kidney (189)": "Kidney",
        "LPS": "Other (specify)",
        "LPS/HCL": "NHL (HCL (Hairy cell leukemia))",
        "LPS/chronic lymphocytic leukemia": "NHL (CLL (chronic lymphocytic leukemia))",
        "Large intestine": "Colon",
        "Left colon  (C18.6-18.7), 391 cases": "Colon",
        "Left-sided colon cancer": "Colon",
        "Leukemia": "Leukemia",
        "Leukemia (204-207)": "Leukemia",
        "Leukemias (lymphoid and meyeloid leukemias)": "Leukemia (Lymphoid)",
        "Liver cancer": "Liver/hepatocellular carcinoma",
        "Liver cancer (ICD03)": "Liver/hepatocellular carcinoma",
        "Low-stage prostate cancer": "Prostate",
        "Lower third esophagus, squamous cell carcinoma": "Oesophagus (Squamous cell carcinoma)",
        "Lung": "Lung",
        "Lung (162)": "Lung",
        "Lung cancer": "Lung",
        "Lung, men": "Lung",
        "Lung, women": "Lung",
        "Lymphatic and hematopoietic (ICD 200-209)": "Lymphatic and hematopoetic",
        "Lymphocytic leukemia": "Lymphatic and hematopoetic",
        "Lymphocytic lymphoma/B-CLL": "NHL (CLL (chronic lymphocytic leukemia))",
        "Lymphoid leukemia": "Leukemia (Lymphoid)",
        "MM": "MM (Multiple myeloma)",
        "MM (ICD 203)": "MM (Multiple myeloma)",
        "MM (ICD-O M 9732/3)": "MM (Multiple myeloma)",
        "Melanoma": "Malignant melanoma",
        "Meyeloid leukemia": "Leukemia (Myeloid)",
        "Middle third esophagus, squamous cell carcinoma": "Oesophagus (Squamous cell carcinoma)",
        "Multiple Myeloma": "MM (Multiple myeloma)",
        "Multiple myeloma": "MM (Multiple myeloma)",
        "Multiple myeloma (ICD 203)": "MM (Multiple myeloma)",
        "Myeloid leukemia": "Leukemia (Myeloid)",
        "NHL": "NHL (Non-hodgkin's lymphoma)",
        "NHL (200, 202)": "NHL (Non-hodgkin's lymphoma)",
        "NHL (200,202)": "NHL (Non-hodgkin's lymphoma)",
        "NHL (ICD 200 & 200) and CLL (ICD 204.1)": "NHL (CLL (chronic lymphocytic leukemia))",
        "NHL (ICD 200 & 202)": "NHL (Non-hodgkin's lymphoma)",
        "NHL (including Mulitple Myeloma)": "NHL (Non-hodgkin's lymphoma)",
        "NHL (including Multiple Myeloma and CLL)": "NHL (Non-hodgkin's lymphoma)",
        "NHL (including Multiple Myeloma)": "NHL (Non-hodgkin's lymphoma)",
        "NHL and HCL": "NHL (HCL (Hairy cell leukemia))",
        "NHL and Hairy Cell Leukemia": "NHL (HCL (Hairy cell leukemia))",
        "NHL and other respiratory cancers": "Other (specify)",
        "NHL diffuse large cell lymphoma": "NHL (DLBCL (Diffuse large B-cell lymphoma))",
        "NHL extranodal": "NHL (Non-hodgkin's lymphoma)",
        "NHL follicular lymphoma": "NHL (Follicular)",
        "NHL histologic type: other": "NHL (Non-hodgkin's lymphoma)",
        "NHL nodal": "NHL (Non-hodgkin's lymphoma)",
        "NHL-Nodal": "NHL (Non-hodgkin's lymphoma)",
        "NHL-extranodal": "NHL (Non-hodgkin's lymphoma)",
        "NHL: diffuse": "NHL (DLBCL (Diffuse large B-cell lymphoma))",
        "NHL: follicular": "NHL (Follicular)",
        "NHL: small lymphocytic": "NHL (Non-hodgkin's lymphoma)",
        "NR": "Other (specify)",
        "Non-Hodgkin's lymphoma": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodgkin's lymphoma  (ICD-O-2)": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodgkin's lymphoma  (ICD-O-3)": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodgkin's lymphoma (ICD 10)": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodgkin's lymphoma (ICD O-2 based on SEER codes)": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodgkin's lymphoma (ICD-9 200&202)": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodgkin's lymphoma (ICD-O)": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodgkin's lymphoma (WHO definition)": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodgkin's lymphoma WHO definition 2004": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodgkin's lymphoma mortality (ICDO3)": "NHL (Non-hodgkin's lymphoma)",
        "Non-Hodkin's lymphoma (ICD-9 200&202)": "NHL (Non-hodgkin's lymphoma)",
        "Oesophageal adenocarcinoma": "Oesophagus (Adenocarcinoma)",
        "Oesophagus": "Oesophagus",
        "Oesophagus ": "Oesophagus",
        "Oesophagus (ICD-C15?); squamous cell carcinoma": "Oesophagus (Squamous cell carcinoma)",
        "Oesophagus (ICD-O 150, 151)": "Oesophagus",
        "Oesophagus (ICD-O 150, 151) excluding 150.0 and 150.3": "Oesophagus",
        "Oesophagus (ICD-O 150.0-150.9)": "Oesophagus",
        "Oesophagus (ICD-O 15?)": "Oesophagus",
        "Oesophagus (ICD-O 15?) - Sqamous cell cancer": "Oesophagus (Squamous cell carcinoma)",
        "Oesophagus (ICD-O 15?) - Squamous cell cancer": "Oesophagus (Squamous cell carcinoma)",
        "Oesophagus (ICD-O 15?) - Squamous cell carcinoma": "Oesophagus (Squamous cell carcinoma)",
        "Oesophagus (ICD-O 9th edition 150.0-0.9)": "Oesophagus",
        "Oesophagus (ICD-O C15?)": "Oesophagus",
        "Oesophagus (ICD-O-3 C15.0-C15.9) - Squamous cell carcinomas (histology codes 8050-8076)": "Oesophagus (Squamous cell carcinoma)",
        "Oesophagus (ICD-O-3 C15.0-C15.9); Adenocarcinomas (histology codes 8140, 8141, 8190-8231, 8260-8263, 8310, 8430, 8480-8490, 8560, 8570-8572)": "Oesophagus (Adenocarcinoma)",
        "Oesophagus (ICD-O-3 C15.0-C15.9); Squamous cell carcinomas (histology codes 8050-8076)": "Oesophagus (Squamous cell carcinoma)",
        "Oesophagus (ICD9-150 or ICD10-C15)": "Oesophagus",
        "Oesophagus, all": "Oesophagus",
        "Oesophagus, directly interviewed": "Oesophagus",
        "Oesophagus, females": "Oesophagus",
        "Oesophagus, males": "Oesophagus",
        "Other  lymphoma subtypes": "Lymphatic and hematopoetic",
        "Other and ill-defined cancer (ICD 171, 194-199)": "Other (specify)",
        "Other respiratory cancers": "Respiratory tract",
        "Other specified B-cell lymphoma": "B-cell lymphoma",
        "Other type NHL": "NHL (Non-hodgkin's lymphoma)",
        "Other urinary": "Other (specify)",
        "Ovary (183)": "Ovary",
        "Pancreas": "Pancreas",
        "Pancreas (C25)": "Pancreas",
        "Pancreas (ICD-9 157)": "Pancreas",
        "Pancreas (ICD-9 157.0-157.9)": "Pancreas",
        "Pancreas (ICD-O-2 C250-253, C257-C259)": "Pancreas",
        "Pancreas ICD-9, females": "Pancreas",
        "Pancreas ICD-9, males": "Pancreas",
        "Pancreas ICD-O-2 (C25.0-25.3, C25.7-25.9), all": "Pancreas",
        "Pancreas ICD-O-2 (C25.0-25.3, C25.7-25.9), females": "Pancreas",
        "Pancreas ICD-O-2 (C25.0-25.3, C25.7-25.9), males": "Pancreas",
        "Pancreas ICD-O-3, females": "Pancreas",
        "Pancreas ICD-O-3, males": "Pancreas",
        "Pancreatic cancer": "Pancreas",
        "Pancreatic cancer diagnoses were confirmed by participants’ physicians and by the Surveillance, Epidemiology and End Results (SEER) abstracts.": "Pancreas",
        "Prostate": "Prostate",
        "Prostate (185)": "Prostate",
        "Prostate cancer": "Prostate",
        "Prostate cancer (all cases": "Prostate",
        "Prostate cancer (all cases)": "Prostate",
        "Prostate cancer - Aggressive": "Prostate (Aggressive/Advanced)",
        "Prostate cancer - No family history": "Prostate",
        "Prostate cancer - With Family History": "Prostate",
        "Proximal colon": "Colon",
        "Proximal colon (C18.0-18.5), females": "Colon",
        "Proximal colon (C18.0-18.5), males": "Colon",
        "Proximal colon (C180-C184)": "Colon",
        "Proximal colon (ICD-O version 2), females": "Colon",
        "Proximal colon (ICD-O version 2), males": "Colon",
        "Proximal colon (proximal (cecum to splenic flexure), both genders": "Colon",
        "Proximal colon , both genders": "Colon",
        "Proximal colon cancer": "Colon",
        "Proximal colon, 234 cases": "Colon",
        "Proximal colon, 234cases": "Colon",
        "Proximal colon, females": "Colon",
        "Proximal colon, males": "Colon",
        "Rectal (C20), among men and women combined": "Rectum",
        "Rectal (C20), among men only": "Rectum",
        "Rectal (C20), among women only": "Rectum",
        "Rectal Cancer": "Rectum",
        "Rectal cancer": "Rectum",
        "Rectal cancer (ICD-O-1: 154.1)": "Rectum",
        "Rectal cancer (ICD-O-2: C199, C209)": "Rectum",
        "Rectal cancer (ICD-O-2: C199, C209) ": "Rectum",
        "Rectal cancer (ICD-O-2: C199, C209) among carriers of XPD Lys751Gln (rs131181) Lys/Gln or Gln/Gln genotype": "Rectum",
        "Rectal cancer (ICD-O-2: C199, C209) among carriers of XPD Lys751Gln (rs131181) Lys/Lys genotype": "Rectum",
        "Rectal cancer (females)": "Rectum",
        "Rectal cancer (males)": "Rectum",
        "Rectal cancer APC+ (ICD-O: 154.1)": "Rectum",
        "Rectal cancer APC- (ICD-O: 154.1)": "Rectum",
        "Rectal cancer among females": "Rectum",
        "Rectal cancer among males": "Rectum",
        "Rectosigmoid (C19.0) and rectum (C20.9), both genders": "Rectum",
        "Rectum": "Rectum",
        "Rectum (C19-C20)": "Rectum",
        "Rectum (C19-C20) , males": "Rectum",
        "Rectum (C19-C20), 474 cases": "Rectum",
        "Rectum (C19-C20), females": "Rectum",
        "Rectum (C199, C209)": "Rectum",
        "Rectum , males": "Rectum",
        "Rectum ICD 10 C20": "Rectum",
        "Rectum cancer": "Rectum",
        "Rectum, 158 cases": "Rectum",
        "Rectum, 169 cases": "Rectum",
        "Rectum, 195 cases": "Rectum",
        "Rectum, 230 cases": "Rectum",
        "Rectum, females": "Rectum",
        "Respiratory cancers": "Respiratory tract",
        "Right colon  (C18.0-18.5), 351 cases": "Colon",
        "SLL, CLL, MCL": "NHL (SLL/CLL)",
        "SLL,CLL,MCL": "NHL (SLL/CLL)",
        "STS": "STS (Soft tissue sarcoma)",
        "STS (171)": "STS (Soft tissue sarcoma)",
        "STS (ICD 171)": "STS (Soft tissue sarcoma)",
        "Small lymphocytic NHL": "NHL (Non-hodgkin's lymphoma)",
        "Soft tissue sarcoma": "STS (Soft tissue sarcoma)",
        "Squamous cell cancer of the oesophagus (ICD-10 15.3-15.5)": "Oesophagus (Squamous cell carcinoma)",
        "Squamous cell carcinoma of the oesophagus (ICD-9 code 150)": "Oesophagus (Squamous cell carcinoma)",
        "Squamous cell carcinoma of the oesophagus (ICD-9 code 150) - Lower third": "Oesophagus (Squamous cell carcinoma)",
        "Squamous cell carcinoma of the oesophagus (ICD-9 code 150) - Middle third": "Oesophagus (Squamous cell carcinoma)",
        "Squamous cell carcinoma of the oesophagus (ICD-9 code 150) - Upper third": "Oesophagus (Squamous cell carcinoma)",
        "Squamous+Small+Large Cell, all, women": "Stomach/gastric cancer",
        "Stomach": "Stomach/gastric cancer",
        "Stomach ": "Stomach/gastric cancer",
        "Stomach (151)": "Stomach/gastric cancer",
        "Stomach (ICD-O 16.0-16.9)": "Stomach/gastric cancer",
        "Stomach (ICD-O 16?)": "Stomach/gastric cancer",
        "Stomach (ICD-O 16?) - Adenocarcinoma (all)": "Stomach/gastric cancer",
        "Stomach (ICD-O 16?) - Adenocarcinoma (diffuse type)": "Stomach/gastric cancer",
        "Stomach (ICD-O 16?) - Adenocarcinoma (intestinal type)": "Stomach/gastric cancer",
        "Stomach Cardia (ICD-O-3 C16.0) - Adenocarcinomas": "Stomach/gastric cancer",
        "Stomach Cardia (ICD-O-3 C16.0); Adenocarcinomas": "Stomach/gastric cancer",
        "Stomach ICD-O-3": "Stomach/gastric cancer",
        "Stomach ICD9": "Stomach/gastric cancer",
        "Stomach Non Cardia (ICD-O-3 C16.1-C16.9) - Adenocarcinomas": "Stomach/gastric cancer",
        "Stomach Non Cardia (ICD-O-3 C16.1-C16.9); Adenocarcinomas": "Stomach/gastric cancer",
        "Stomach, adenocarcinoma": "Stomach/gastric cancer",
        "Stomach, females": "Stomach/gastric cancer",
        "Stomach, males": "Stomach/gastric cancer",
        "T cell lymphoma": "NHL (T-cell)",
        "T-cell  lymphoma": "NHL (T-cell)",
        "T-cell lymphomas": "NHL (T-cell)",
        "T162": "Lung",
        "Testicular cancer": "Testis",
        "Testicular germ cell tumors": "Testis",
        "Testis": "Testis",
        "Testis cancer  (ICD-O-2)": "Testis",
        "Testis cancer (ICD-O-2)": "Testis",
        "Total NHL": "NHL (Non-hodgkin's lymphoma)",
        "Total leukemia": "Leukemia",
        "Total prostate cancer": "Prostate",
        "UCC": "Kidney",
        "UCC (high risk)": "Kidney",
        "UCC (low risk)": "Kidney",
        "Unspecified B-cell lymphoma": "B-cell lymphoma",
        "Unspecified non-Hodgkin lymphoma": "NHL (Non-hodgkin's lymphoma)",
        "Upper third esophagus, squamous cell carcinoma": "Oesophagus (Squamous cell carcinoma)",
        "Urinary bladder cancer": "Urinary bladder",
        "Urinary bladder carcinoma (incl. in situ)": "Urinary bladder",
        "Uterus (180)": "Uterus/uterine corpus",
        "We asked for permission to obtain  related medical records or pathology reports": "Other (specify)",
        "adenocarcinomas of the esophagus and the esophagogastric junction": "Oesophagus (Adenocarcinoma)",
        "all cancers": "All cancers combined",
        "all neoplasms (ICD-9 140-208)": "All cancers combined",
        "as above": "Other (specify)",
        "bladder cancer": "Urinary bladder",
        "childhood brain cancer (ICD-O 191)": "Brain (Childhood cancer)",
        "chronic lymphocytic leukemia": "NHL (CLL (chronic lymphocytic leukemia))",
        "colon": "Colon",
        "colorectal (ICD-9 153-154)": "Colon & rectum",
        "colorectal cancer": "Colon & rectum",
        "colorectal cancer incidence": "Colon & rectum",
        "colorectal cancer mortality": "Colon & rectum",
        "digestive cancer": "Other (specify)",
        "endometrial cancer": "Endometrium",
        "esophageal cancer, 1162 cases": "Oesophagus",
        "esophagus": "Oesophagus",
        "esophagus ICD-10rev": "Oesophagus",
        "esophagus ICD-O-3": "Oesophagus",
        "esophagus, squamous cell carcinoma": "Oesophagus (Squamous cell carcinoma)",
        "follicular": "NHL (Follicular)",
        "gastric adenocarcinoma": "Stomach/gastric cancer",
        "gastric cancer (ICD10 : C16)": "Stomach/gastric cancer",
        "genital and urinary tract cancer ": "Other (specify)",
        "germ cell testicular cancer": "Testis",
        "hepatocellular carcinoma": "Liver/hepatocellular carcinoma",
        "hepatocellular carcinoma (ICD03)": "Liver/hepatocellular carcinoma",
        "hepatocellular carcinoma (ICD10)": "Liver/hepatocellular carcinoma",
        "high stage prostate cancer": "Prostate (Aggressive/Advanced)",
        "histologically confirmed cancer": "Other (specify)",
        "intracranial glioma (ICD-O 938-948)": "Brain (Glioma)",
        "intracranial glioma cases ": "Brain (Glioma)",
        "leukemia ": "Leukemia",
        "leukemia (ICD-9 204-208)": "Leukemia",
        "leukemia (including myelodysplasias)": "Leukemia",
        "leukemia (men)": "Leukemia",
        "leukemia (women)": "Leukemia",
        "lip": "Lip",
        "liver": "Liver/hepatocellular carcinoma",
        "liver cancer": "Liver/hepatocellular carcinoma",
        "lung": "Lung",
        "lung cancer": "Lung",
        "lung cancer (ICD-9 162)": "Lung",
        "lung cancer incidence": "Lung",
        "lung cancer mortality": "Lung",
        "lung-Adenocarcinoma": "Lung (Adenocarcinoma)",
        "lung-Other Carcinomas": "Lung",
        "lung-Small cell Carcinoma": "Lung (Small cell/Oat cell)",
        "lung-Squamous cell Carcinoma": "Lung",
        "lymphatic and haetopoietic cancer": "Lymphatic and hematopoetic",
        "lymphatic-hematopoietic": "Lymphatic and hematopoetic",
        "lymphocytic leukemia": "Leukemia (Lymphoid)",
        "lymphohematopietic (ICD-9 200-208)": "Lymphatic and hematopoetic",
        "lymphohematopoietic (ICD-9 200-208)": "Lymphatic and hematopoetic",
        "lymphoid leukemia ": "Leukemia (Lymphoid)",
        "malignant melanoma": "Malignant melanoma",
        "melanoma (ICD-9 172)": "Malignant melanoma",
        "multiple myeloma": "MM (Multiple myeloma)",
        "non-Hodgkin's lymphoma": "NHL (Non-hodgkin's lymphoma)",
        "noncardia gastric cancer": "Stomach/gastric cancer",
        "oesophageal cancer": "Oesophagus",
        "oesophagus cancer (adenocarcinoma)": "Oesophagus (Adenocarcinoma)",
        "other B-cell": "Other (specify)",
        "ovarian cancer": "Ovary",
        "ovarian cancer (ICDO = 183.0)": "Ovary",
        "ovarian cancer ICD-0-3": "Ovary",
        "ovarian cancer ICD-10 C56": "Ovary",
        "ovarian cancer ICD-O-2 C56": "Ovary",
        "panceras ": "Pancreas",
        "pancreas": "Pancreas",
        "pancreas (C25)": "Pancreas",
        "pancreas (ICD 10: C25)": "Pancreas",
        "pancreas (ICD 10=C25)": "Pancreas",
        "pancreas (ICD-O-3 code C250-C259). Endocrine tumors were deleted.": "Pancreas",
        "pancreas (ICDO-3 81503, 82463, and 88903 were excluded)": "Pancreas",
        "pancreas ICD-9 revision 157 excluding 157.4": "Pancreas",
        "pancreas ICD-O-2 (C25.0–C25.3 and C25.7–C25.9)": "Pancreas",
        "pancreas ICDO-3": "Pancreas",
        "pancreas ICDO-3 C25.0-25.3, 25.7-25.9 (histology type 8150-55, 8240, 8246, 8502 were excluded)": "Pancreas",
        "pancreas ICDO-3 C25.0-25.3, C25.7-25.9 (histology type 8150-8155, 8240, 8246, and 8502 was excluded)": "Pancreas",
        "pancreas death ICD-10 C25": "Pancreas",
        "pancreas, ICDO-3": "Pancreas",
        "pancreatic Cancer": "Pancreas",
        "pancreatic cancer": "Pancreas",
        "prostate": "Prostate",
        "prostate (agressive)": "Prostate (Aggressive/Advanced)",
        "prostate (no family history)": "Prostate",
        "prostate (total)": "Prostate",
        "prostate (yes family history)": "Prostate",
        "prostate cancer": "Prostate",
        "prostate cancer (ICD-9 185)": "Prostate",
        "renal adenocarcinoma": "Kidney",
        "renal cell cancer O-2": "Kidney",
        "renal cell cancer O-2 C.64": "Kidney",
        "renal cell carcinoma": "Kidney",
        "renal cell carcinoma (ICD-9 189.0)": "Kidney",
        "renal cell carcinoma C649": "Kidney",
        "repiratory cancer": "Respiratory tract",
        "squamous cell carcinoma of the esophagus, \"Black\" male": "Oesophagus (Squamous cell carcinoma)",
        "squamous cell carcinoma of the esophagus, \"White\" male": "Oesophagus (Squamous cell carcinoma)",
        "stomach": "Stomach/gastric cancer",
        "stomach (ICD 151)": "Stomach/gastric cancer",
        "stomach (ICD-O 16.0-16.9)": "Stomach/gastric cancer",
        "stomach (ICD-O 161-166, 168, 169)": "Stomach/gastric cancer",
        "stomach (ICD-O-2)": "Stomach/gastric cancer",
        "stomach (ICD9th rev)": "Stomach/gastric cancer",
        "stomach 151(ICD-9)": "Stomach/gastric cancer",
        "stomach 151.0-159.0(ICD-9) and 16.0-16.9 (ICD-10), females": "Stomach/gastric cancer",
        "stomach 151.0-159.0(ICD-9) and 16.0-16.9 (ICD-10), males": "Stomach/gastric cancer",
        "stomach ICD-10rev": "Stomach/gastric cancer",
        "stomach ICD-O-3": "Stomach/gastric cancer",
        "stomach cancer": "Stomach/gastric cancer",
        "stomach cancer (adenocarcinoma)": "Stomach/gastric cancer",
        "testicle": "Testis",
        "testicular cancer": "Testis",
        "testicular cancer / non-seminoma": "Testis (non-seminomas)",
        "testicular cancer / seminoma": "Testis (seminomas)",
        "total NHL": "NHL (Non-hodgkin's lymphoma)",
        "total leukemia": "Leukemia",
        "xxx": "Other (specify)",
        "β-HCH": "NHL (Non-hodgkin's lymphoma)",
    },
    getUniquesSorted = function(arr){
        return _.chain(arr)
            .sort()
            .uniq(true)
            .value();
    },
    getMissings = function(){
        // get complete list of all current organSite values
        var vals = [];
        db.epiResult
            .find()
            .forEach(function(d){
                var site = d.organSite;
                if (siteMap[site] === undefined){vals.push(site);}
            });
        vals = getUniquesSorted(vals);
        _.each(vals, function(d){print("Missing: |" + d + "|");});
        return vals.length;
    },
    setValues = function(){
        var missingCategories = [];
        db.epiResult
            .find()
            .forEach(function(d){
                var organSiteCategory = siteMap[d.organSite];
                if (organSiteCategory === ""){
                    missingCategories.push(d.organSite);
                }
                if (d.organSiteCategory !== organSiteCategory){
                    db.epiResult.update(
                        { _id: d._id },
                        {$set: {organSiteCategory: organSiteCategory}});
                    print("Updated: " + d._id);
                }
            });

        missingCategories = getUniquesSorted(missingCategories);
        _.each(missingCategories, function(d){print("Missing category: " + d);});
    },
    printPlacement = function(){
        // For each category, print all organSites associated
        var cats = {};
        _.each(siteMap, function(cat, str){
            if (cats[cat] === undefined) cats[cat] = [];
            cats[cat].push(str);
        });
        var rows = [];
        _.chain(cats)
            .keys()
            .sort()
            .each(function(cat){
                rows.push(cat + '\t');
                var val = getUniquesSorted(cats[cat]);
                val.forEach(function(d){
                    rows.push('\t' + d);
                });
            });
            print(rows.join('\n'));
    },
    printByTable = function(){
        var rows = [];
        db.epiResult
            .find()
            .forEach(function(d){
                rows.push(d._id + '\t' + d.organSiteCategory + '\t' + d.organSite + '\t' + d.tbl_id);
            });
        print(rows.join('\n'));
    };


var missings = getMissings();
if (missings === 0) setValues();
// printPlacement();
// printByTable();
