
// category renaming
db.epiResult.update(
    {organSiteCategory: "Head and neck"},
    {$set: {organSiteCategory: "Upper aerodigestive tract"}},
    {multi: true}
);

db.epiResult.update(
    {organSiteCategory: "B-cell lymphoma"},
    {$set: {organSiteCategory: "NHL (B-cell lymphoma)"}},
    {multi: true}
);

var ids = [
        'rc7jmtZqtaA7jeY5N',
        '24W54GhBKdKuHCgKt',
        'mtyZ7eKRiirAmSjWF',
        'CdtHqQSBQeR7n4BMp',
        'YCnBEDf2f4N9gMXmK',
        'tctnDhuuuK45vFtNF',
        'EPkQwxubu9pkTBA3z',
        'zQ3skofwgnv77pdZa',
        'eYz3e7oFjyY7pe32c',
        'YDNYqRcQb2JotxpEY',
        'zzeoKKQfNNs7JyAPi',
        'aDp2bnuEsTJFTETmu',
        'HbJWqcrrjWHhbEDyc',
        'bSGb4Gn5LfEht4Jn3',
        '5oEX8Shvopmt7wQMZ',
        'ynJSn4R9DJcf5y86Y',
        'wm2cwWGukFHryq5T8',
        'YsaEcTvLkQk3rgn2R',
        'CGr4GZLydiuTyyHsA',
        'efuhpCA9TR84HFZan',
        '6syBbHbnTtMTuJcBL',
        'obg5EQdE4SZcXkbd4',
        'Y7cJu4M7eQQonifqu',
        'uQrTE4YP9BWHD2gL8',
        'wWgoDNGjkb2MakdDb',
        'YDdEkuyNGziZv7xnW',
        'Gten9rAPqgThM9G29',
        'ATSxiGpQkx4BEXns6',
        'p6fNZFRauCanuNndh',
        'AtT4AHqJB8Dva2gCK',
        'qDfBX7X2TYRy2xD7k',
        'LLYhHYtjdrwMbMPAZ',
        'JEMHGFikfe7tRGNDg',
        'WtTNN9ipr6GG3uYXm',
        'MdoQQqwDSTimrq4uN',
        'QN25jTJWh75PrByHr',
        '3vHc35dHGr3MSZomR',
        'TDt3MARWnaaccPdBG',
        'vSNeJ9Lmvf3eXujoX',
        '2ynx2RvnAT86WaCqG',
        'NumgBwTiptZ8pqEQb',
        'if5uYKp2R33nSgY5x',
        'TGG8AtbqGYAYfZnoZ',
        'BSniasnBzsapaTx5m',
        'LcjLp9dpa6yCehf2c',
        'gohMkgHAWxgBdtHy5',
        'sefaKideCDwNDWBcj',
        'j2jBPBifw8Fe87uFZ',
        'iLZHEcQDnnCCiHgrN',
        'WPJGfzp55czwgZcN8',
        'WNixucNK7vt9D3EWE',
        'cpRb5ayBJL4E9q3xs',
        'f4Cc2DXk3Y27eeMpo',
        '7voh3zZocDkEx4HiL',
        'MRRLabJKcRufQ54dN',
        'QqYNarfkBDunBsBnA',
        'noP6hiMR8YTryrzEF',
        'vwZYt6vrdKwnXYjAH',
        '6ATA4Nz5jKQhCGmF3',
        's2AjnbhcybkyiXaGZ',
        'FiFbGKASNQH74az6f',
        'LyPnCYNPhNZrMfHe6',
        '2hXZCzTdvb5tG8ZJR',
        'RFPjQC5r6XK4NzdZg',
        'oZihi5cF52PhY6evK',
        'QJDMgNXEGMBhsXKSd',
        '3cuSx4yZDxvupfcMi',
        'yKzkK6zBkXB2oNxRL',
        'hHBYrA4DgCosD53tN',
        'LNuBQFvEfiJx852S8',
        '9TF63RHPcQ7zHixR2',
        'pCQC7nFu4jnR5PzgE',
        'dnshxmSccY8Kw22kF',
        'LKC9jpz5FchxNJhLh',
        'i5EmHmBYbaRhQTWdN',
        '6fqDhw67iRsegFCTs',
        'M8h89BYA3o9shExuc',
        'aHncMR2EwJ69BXPFh',
        'tZBGgq22ThM3YdLjy',
        'YQTtgdGGyPbyhKB8E',
        '8cDeN7o7zHK5wPAmN',
        '37SJ5xgFYLutpXqiX',
        'DDc5ESoCTJLA42sBk',
        'CzNnT4u3LpAgXT8Zo',
        'QnTevWcWuDR2WBLMP',
        '6ypN7jwCFJ9zMqZTG',
        'geTrTYgZ6QspY8Lm2',
        'zmCX6rz4hCfLaCdTc',
        'qEBLoMJ4RGaKA7qHj',
        'wo2Zbf2n5tLJyD7rJ',
        'tc5fmCjowYzXYEx5L',
        'trPSDi2WijaZdBRGt',
        'DLeRmT7ezxbaBjdWK',
        '3HyfqKFj2f6HH7Aqa',
        'DRXZNs3tFsD9bF5LK',
        'ccfmqawGqWPir2mS4',
        'SiLaANx2TcmnxY9Fz',
        'vy2g8c7qDgz9LRWaZ',
        '4mjdasTpCS6yQqL5F',
        'mXfoXye7a77Mozwfs',
        'qn3izTYiRGH66nKTG',
        '6c28MMq2YQpoNf4yt',
        'vaJeCMsBBsFZ4LSjb',
        '2RHb5J2rk8o7cXYMS',
        'ozzgXqxz7dhPg6rXN',
        '68DmQ6uhrtY7Cruhy',
        'ba7xmPsjaCRzZp5SE',
        'DjHFzB6vPhKNdLjp6',
        'fKMjjsh4pxma8dwuS',
        'nBT8wq7Cv2BMGpaGX',
        'WNNESRgq8EaxkhYwz',
        'pSrJ4nvNsapxCnCJp',
        'y2ajxPY3de7MTeJHc',
        'EcPfHkQTPAbFnojLR',
        '8c6BqtuPswo497E4T',
        'BEZFy8GoQFRtbaTGf',
        'JqJzs9SmJZNBir9Rg',
        'AjPahX4Ko22meET3i',
        'GoNzhNnMfnMMgR9F5',
        'J8DdYEpaKqYyRADXF',
        'hk8kr8RnTaFfbHfHz',
        'BbMWQAEd3JtvAFhZX',
        'H82rwSnE59p43jze6',
        'DBAi8pyGdm58ZRfMq',
        'HtmJEekMwC2bjAiKK',
        'bdBvT9NjM6QdHqP2b',
        'QtE6uwADaSxjjZMwk',
        'Dh8JiqLMKzv8gsTyv',
        'JN2X55oiWSB7mFfis',
        'm9vxJT9t8zfGfJabr',
        'RkCnkBcggqLCzBk7s',
        'AhyfWPo32xPavRWfS',
        '22J6CsooehmGRX8Ai',
        'w5wpwis4cfYSkJBbs',
        'z7DhYCrqCqdgztQyP',
        'CcszhRQvQdNHZmfPv',
        '2EvFsFWYxazyTNtEe',
        'j7ojgJWr54o6ZzmSK',
        'nZs7NN52EGE7RcTvW',
        '8Nm4Tn7fEsunhjDty',
        '8aakfhZmhmYFfyvrz',
        'nqYyKFj6kxPsCxoGo',
        'fYxbH4xRvANMdpDJe',
        '8MCq6KNXwyg9Q3PJ4',
        'YKbb3F2srNBD8BbE4',
        'qGSEvWMDJFRa2xXe4',
        '7SNRawRCNcoxKxwNf',
        'uyp2NHDTM3tTsNYdf',
        'ubDewTGZeL65SvyFp',
        'p6yygMKs2BBKgPKg2',
        'RKFkigeqQBBcCHaiR',
        'e2jfsGKqFZoxY5Z32',
        'e95YmZSiuo3dZ6GXR',
        'GYYaaGpRGMzeTPGGu',
        'snutJDGGjH7hpMc25',
        'oM6od7Cv9TReyvZ6n',
        'M9rXYzfC5mXuAjtmC',
        'HvJHTRPDkhyP49Wce',
        'XLgRAxqmk2zXAhvFN',
        'JYN2oFRJdEiY8sYAM',
        'mkhJsH9oJaqWraPgY',
        'Qkzbwai8mDfXfkoLF',
        'kax9oyJbozysRpW3H',
        'ny27uY88HErxMWNRT',
        'j7ubK8rstxRKYjqw7',
        'FogwJdaNTyGgNqRwB',
        'GjBjv74xWnCwXQ5xH',
        'ehMdpSMrAzbegRYoB',
        'Pb6t89EcAWMyBPgSG',
        'k8TNsZ3Fjdj6J3Y2W',
        'nggrCwf43uTu2Aqsp',
        'fYz2pnEeiNEYjRP2S',
        'eaKZDCPMqQqxr6gQ5',
        'htjoTwMJ8P6dYAHTA',
        'wDykKF2PmaEaRRre2',
        'mgdJ3kfwm7PXaA8XQ',
        'euh6dXrpxKTXRRQN4',
        'QMzFPz7GeDQp6mn2C',
        'SvSvm2opiwT7n6KPe',
        'GDZStToNHA7SYPHsg',
        'sXxvgYuScyRwaPEGK',
        'ucaoSY2iy462u8jNY',
        'wekNxK8rHK5d2DrZ4',
        '8aK8GqwN8s3f3s6Kz',
        'SWYXYPAPgJF8NK9RP',
        'zaZ6Enbuv7pXtPMpy',
        'oHQJkj3JaQyr8fAfM',
        'dZ6tQpj837Dk8n2qj',
        '5vQKPWfMQE8iTJP7L',
        'nXTxwtrz3q4HoYyXx',
        '6hZqH6LtpvPDAWoPt',
        'eqhDq289X3ZCydi9F',
        'TF6iqaM3Xy3ba9dma',
        'TGQcxyPRkY3WcCeZu',
        'vEyGsCvGK5kcee2ho',
        'BE8JCMs88KXKXJkYc',
        '8N8tLRtWvAdnB7SSX',
        'EuHRApET5xrm4EcjD',
        'FtYTeGcQGCWwkDYoC',
        'qim3y9Srv2NcfTqrc',
        'dLi7b2nSfMivi6r2a',
        'ihdMxYoEmGN5ujBqT',
        'W8Aq5hfszYpwJtfNS',
        'uxBeRyNBrRHtRLnA7',
        'JLugbDjhoHPdEkzsg',
        'sYTd4GXeppCoGe2mD',
        'htSHhyRK55qDNHNJ8',
        'p8jGM5CfPzXKCZZ45',
        'rpHmkBnnvRYnTimgb',
        'mwwtfPGC7uRHPNLxC',
        '4Ba9mqQNszkAEmcS2',
        '4GYDCLmif26AWcroM',
        'WECn27Kci2tcpG4mR',
        'u447tWX55hDtLTRpo',
        'DoDrD3D3J8iXHLQAW',
        '7QBDJ5NAtSgZG8ibT',
        'r9EnqYAQjr4MvjjRa',
        'JpJxamh3cTHwqxMjp',
        'H3HS76NPL4pGZorao',
        '8k4WaDY6ANCd3Phh6',
        '8b2bYBMYGAZYqDSsi',
        'tqLnkP2N8iQ8mtWMo',
        'rzz6fQ92xh97budBf',
        'PAxkmdHJom4L8nAAN',
        'mucEQFznbAotCnDj4',
        'hmYzFBo4xYgJKbEHw',
        'jGKrvRhmqmjNrRR4u',
        'jWkyMPJi2qWaRvSd7',
        'ANTgdwyGM9oriLkwy',
        'CR3SsjC3WxGQAQdPL',
        'AfpYMrnngKt5hCuGb',
        'qe98MgJnjf59c2CtK',
        '3HXawWaoF8YKbCbw3',
        '4sbdDmoWLHp6tJHBu',
        'dwmDHfiJNNm5d45b7',
        'Ei8BG7gL8iTTNf4pm',
        'NBSw5XRrv28GXybSs',
        'mk6LQJWSanwj6fEPZ',
        'mcJfBr5b8W36q3o4z',
        'RmxFyDDPbYmCABg6G',
        'twu35LT2xc5NhpGam',
        'wx2gaagpthpEfciWZ',
        'zdxvRZT2KR9bMKFJr',
        'THHjgrCJifySXYNw2',
        'xWCm4R9LHDnNGoSM2',
        'EvxkNh7dmAKouXAo8',
        'qC57KRRCBY7pmdJs3',
        'pFghPcPCjCxBWyh9j',
        'oWkpD4zLSRPbDvqcB',
        'o8jMffMr3rk8z5qFb',
        'DLowEtjNSHTvBobaW',
        'dsbQsXPdiEamxjBwG',
        'sKcDrXNk2L4G4PsJh',
        'SvevakipyAgnemxZ7',
        'P39CZ3WEpupTYmHCF',
        'kibTgCwmdGZu2kGZj',
        'Z4FDkhXjty3jNBG84',
        'NxJFKFQmuYJP5G7fW',
        'h8oPJcvHmMiopk6Gr',
        'AcQjvj6NB8SszzpoX',
        'ntCyYwTWsNdXWT7Ek',
        'ph6tgHEiWNP6si43i',
        'tfXv4yYgkF5NsRJ2d',
        'MjY2iBsGXLiJ6mLNj',
        'g8nLXXmKyJvh9z3zi',
        'rprsS3AyzZavSZYnu',
        'HLtSjqxdoYidSqXbd',
        'E9G76yTuz8mbW49rC',
        'pEKH7vjX9KYBvvTGc',
        'bASaAmNFuHfJH68Qr',
        'S8ZHXZzdGHsBoE4X7',
        'zAH2Avf56hawc3m3Y',
        'Ln6agH7uy2jtZJhpK',
        'd2SKgApEyq7AydnKA',
        'mZm8PvxfBtntnQraf',
        'AvBkcTXE4ueYxtf6W',
        'SiLkHRCMS6pZftQXR',
        'e34Ps69v5rqXz8LPg',
        'JuYzCdojoS69WW5Cg',
        'TWDTGjX7kT8tjF7pX',
        '3nX8DKYTMoL8Lo864',
        'ZB5WbnBBEGhiCuJkx',
        'XbjxxKEfSrhAKDHbz',
        'ikPstHzCHNP6qbhJK',
        'kA8eSNL8DsgdmRyL4',
        'qZpmnwXgTa2WL625x',
        'XRLgxYd7nj9qDEksj',
        '3cJEpgbLQp4SQfQHs',
        '6uJbgRhw9SvfYDnJY',
        'mdBZTaD2wnTiyoDMY',
        'MdteE42xSYXTom8sz',
        '6QMpi4BKmBf6cPDcF',
        'xRx2tTD75E85vfzek',
        'mP5BrtqQe4WymdkZp',
        'iRBh2RDZPfSTAjth2',
        '86FowRFTPS7KkkbHG',
        'qmfwPAtva5scT77vs',
        'PqNstCscrGg4XrAgL',
        '4Z4xDtePTcPtAgxTk',
        '3io6CftiBLfMiJTuk',
        'gngAf6DDJJ5bjRbaK',
        'QjFurAZJNpupD5exw',
        'KHfCbMEQi22oSSGvP',
        'M3QJxK3g2XhAiuD7t',
        '5CdLn6J8WJXFmfkGP',
        'fENpCTsTt4HYhHfAv',
        'oteTn3P5HsahryaTQ',
    ],
    categories = [
        "NHL (B-cell lymphoma)",
        "NHL (B-cell lymphoma)",
        "NHL (B-cell lymphoma)",
        "NHL (B-cell lymphoma)",
        "NHL (B-cell lymphoma)",
        "NHL (B-cell lymphoma)",
        "Brain (Glioma)",
        "Brain (Glioma)",
        "Brain (Glioma)",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Colon",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Kidney (renal cell carcinoma)",
        "Urinary bladder",
        "Urinary bladder",
        "Urinary bladder",
        "NHL (CLL (chronic lymphocytic leukemia))",
        "NHL (CLL (chronic lymphocytic leukemia))",
        "NHL (CLL (chronic lymphocytic leukemia))",
        "NHL (CLL (chronic lymphocytic leukemia))",
        "Leukemia",
        "Leukemia",
        "Leukemia",
        "Lung",
        "Lung",
        "Lung (Squamous cell carcinoma)",
        "Lung (Squamous cell carcinoma)",
        "Lung",
        "Lung",
        "Leukemia (Lymphoid)",
        "NHL (Non-hodgkin's lymphoma)",
        "NHL (Non-hodgkin's lymphoma)",
        "NHL (Non-hodgkin's lymphoma)",
        "NHL (Non-hodgkin's lymphoma)",
        "NHL (Non-hodgkin's lymphoma)",
        "HL (Hodgkin's lymphoma)",
        "HL (Hodgkin's lymphoma)",
        "HL (Hodgkin's lymphoma)",
        "HL (Hodgkin's lymphoma)",
        "HL (Hodgkin's lymphoma)",
        "NHL (Non-hodgkin's lymphoma)",
        "NHL (Non-hodgkin's lymphoma)",
        "NHL (Non-hodgkin's lymphoma)",
        "NHL (Non-hodgkin's lymphoma)",
        "Oesophagus (Squamous cell carcinoma)",
        "Oesophagus (Squamous cell carcinoma)",
        "Oesophagus (Squamous cell carcinoma)",
        "Oesophagus (Squamous cell carcinoma)",
        "Other (specify)",
        "Prostate",
        "Prostate",
        "Prostate",
        "Pancreas",
        "Other (specify)",
        "Other (specify)",
        "Pancreas",
        "Pancreas",
        "Other (specify)",
        "Other (specify)",
        "Other (specify)",
        "Other (specify)",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Lung",
        "Lung",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Lymphatic and hematopoetic",
        "Lymphatic and hematopoetic",
        "Other (specify)",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Lung",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Other (specify)",
        "Other (specify)",
        "Other (specify)",
        "Other (specify)",
        "Other (specify)",
        "Other (specify)",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Lung",
        "Lung",
        "NHL (Non-hodgkin's lymphoma)",
        "Other (specify)",
        "Other (specify)",
        "Pancreas",
        "Other (specify)",
        "Other (specify)",
        "Other (specify)",
        "Prostate",
        "Prostate",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Pancreas",
        "Upper aerodigestive tract",
        "Upper aerodigestive tract",
        "Upper aerodigestive tract",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate",
        "Prostate (Aggressive/Advanced)",
        "Prostate (Aggressive/Advanced)",
        "Prostate (Aggressive/Advanced)",
        "Prostate (Aggressive/Advanced)",
        "Prostate (Aggressive/Advanced)",
        "Prostate (Aggressive/Advanced)",
        "Oesophagus (Adenocarcinoma)",
        "Oesophagus (Adenocarcinoma)",
        "Stomach/gastric cancer",
        "Stomach/gastric cancer",
        "Stomach/gastric cancer",
        "Stomach/gastric cancer",
        "Stomach/gastric cancer",
        "Stomach/gastric cancer",
        "Stomach/gastric cancer",
        "Stomach/gastric cancer",
    ],
    objs = _.zip(ids, categories);

// individual object updates
_.each(objs, function(d){
    db.epiResult.update(
        {_id: d[0]},
        {$set: {organSiteCategory: d[1]}},
        {multi: false}
    );
});
