import { SimpleSchema } from 'meteor/aldeed:simple-schema';
import {
    studyDesigns,
    sexes,
    ratings,
    biasDirection,
    biasDirectionPopoverText,
    ratingRationalePopoverText,
} from './constants';


export default {
    // #1: General information
    referenceID: {
        label: 'Reference',
        type: SimpleSchema.RegEx.Id,
    },
    additionalReferences: {
        label: 'References',
        type: [SimpleSchema.RegEx.Id],
        minCount: 0,
        popoverText: 'References of earlier updates or related publications',
    },
    studyDesign: {
        label: 'Data class',
        type: String,
        allowedValues: studyDesigns,
        popoverText: 'As reported',
    },
    // #2: Study design
    species: {
        label: 'Species',
        type: String,
        min: 1,
        popoverText: 'As reported',
        typeaheadMethod: 'searchNtpAnimalSpecies',
        placeholderText: 'Mouse, Rat, Hamster',
    },
    strain: {
        label: 'Strain',
        type: String,
        min: 1,
        popoverText: 'As reported',
        typeaheadMethod: 'searchNtpAnimalStrain',
        placeholderText: 'B6C3F1, F344',
    },

    sex: {
        label: 'Sex',
        type: String,
        allowedValues: sexes,
        popoverText: 'As reported',
    },
    ageAtStart: {
        label: 'Age at start',
        type: String,
        min: 1,
        popoverText: 'Age at start of exposure',
        placeholderText: '6-8 wk old, 2 mo old, newborn',
    },
    duration: {
        label: 'Duration',
        type: String,
        min: 1,
        popoverText: 'Exposure duration including additional observation time (if any)',
        placeholderText: '110 wk, 24 mo, lifetime',
    },
    'historicalDataAvailable': {
        label: 'Historical data available?',
        type: Boolean,
        popoverText: 'Is historical data for this species and strain available in this publication or another?',
    },

    randomizationRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    randomizationDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    randomizationRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },
    concurrentControlsRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    concurrentControlsDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    concurrentControlsRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },

    animalModelSensitivityRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    animalModelSensitivityDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    animalModelSensitivityRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },
    statisticalPowerRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    statisticalPowerDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    statisticalPowerRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },
    // #3: Exposure
    agent: {
        label: 'Agent',
        type: String,
        min: 1,
        popoverText: 'As reported',
        typeaheadMethod: 'searchNtpAnimalAgent',
        placeholderText: 'Trichloroethylene, Asbestos',
    },
    dosingRoute: {
        label: 'Dosing route',
        type: String,
        min: 1,
        popoverText: 'As reported',
        typeaheadMethod: 'searchNtpAnimalDosingRoute',
        placeholderText: 'Gavage, feed, i.p.',
    },
    purity: {
        label: 'Purity',
        type: String,
        min: 1,
        popoverText: 'As reported',
        typeaheadMethod: 'searchNtpAnimalPurity',
        placeholderText: '>99.9%, technical grade',
    },
    vehicle: {
        label: 'Vehicle',
        type: String,
        min: 1,
        popoverText: 'As reported',
        typeaheadMethod: 'searchNtpAnimalVehicle',
        placeholderText: 'distilled water, PBS, saline, air',
    },
    dosingRegimen: {
        label: 'Dosing regimen',
        type: String,
        min: 1,
        popoverText: 'Dosing regimen of the agent tested, and (if any) information on any co-exposure or modifying factors (e.g., NDEA, TPA, Aflatoxin B1, UV) including route, concentration and dosing regimen',
        placeholderText: '2x/d for 103 wk; 2x/wk for 20 mo',
        textAreaRows: 2,
    },

    chemicalCharacterizationRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    chemicalCharacterizationDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    chemicalCharacterizationRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },
    dosingRegimenRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    dosingRegimenDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    dosingRegimenRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },

    exposureDurationRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    exposureDurationDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    exposureDurationRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },
    doseResponseRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    doseResponseDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    doseResponseRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },
    // #4: Outcome
    outcomeMethods: {
        label: 'Outcome methods',
        type: String,
        textAreaRows: 4,
        popoverText: 'Diagnostic procedures used; extent of necropsy tissue evaluation',
    },
    outcomeMethodsRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    outcomeMethodsDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    outcomeMethodsRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },

    groupConsistencyRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    groupConsistencyDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    groupConsistencyRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },
    durationRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    durationDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    durationRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 2,
        popoverText: ratingRationalePopoverText,
    },
    // #5: Confounding
    vehicleToxicity: {
        label: 'Vehicle toxicity issues',
        type: String,
        textAreaRows: 2,
        popoverText: 'Potential carcinogenic or mutagenic contaminants or vehicle concerns',
    },
    animalHusbandry: {
        label: 'Animal husbandry issues',
        type: String,
        textAreaRows: 2,
        popoverText: 'Monitoring for parasites, disease, or housing conditions',
    },
    confoundingRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    confoundingDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    confoundingRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 3,
        popoverText: ratingRationalePopoverText,
    },
    // #6: Analysis and reporting
    statisticalReporting: {
        label: 'Statistical reporting',
        type: String,
        textAreaRows: 4,
        popoverText: '<add>',
    },
    statisticalReportingRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    statisticalReportingDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    statisticalReportingRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 3,
        popoverText: ratingRationalePopoverText,
    },
    tumorCombiningRating: {
        label: 'Bias rating',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    tumorCombiningDirection:{
        label: 'Bias direction',
        type: String,
        allowedValues: biasDirection,
        popoverText: biasDirectionPopoverText,
    },
    tumorCombiningRationale: {
        label: 'Bias rationale',
        type: String,
        optional: true,
        textAreaRows: 3,
        popoverText: ratingRationalePopoverText,
    },
    // #7: Study judgment
    strengths: {
        label: 'Principal strengths',
        type: String,
        optional: true,
        popoverText: 'e.g., GLP study, multiple doses tested, high number of animals per group',
        textAreaRows: 4,
    },
    limitations: {
        label: 'Principal limitations',
        type: String,
        optional: true,
        popoverText: 'e.g., inadequate duration, no controls, small number of animals per group, inadequate reporting of exposure or results, high mortality, MTD not reached',
        textAreaRows: 4,
    },
    overallUtility: {
        label: 'Overall utility',
        type: String,
        allowedValues: ratings,
        popoverText: ratingRationalePopoverText,
    },
    overallUtilityRationale: {
        label: 'Overall utility rationale',
        type: String,
        optional: true,
        textAreaRows: 3,
        popoverText: ratingRationalePopoverText,
    },
};
